// Shop code enum (datatype)
enum
{
	AUTO_BHOP
	, GRAY_AMMO
	, GREEN_AMMO
	, BLUE_AMMO
	, GOLD_AMMO
	, RED_AMMO
	, SF_SIZE
}

// Special functoins
stock char g_sSF[][] =
{                     				// Function ID:
	"AUTO_BHOP",	  				// 0
	"GRAY_AMMO",	  				// 1
	"GREEN_AMMO",	  				// 2
	"BLUE_AMMO",	  				// 3
	"GOLD_AMMO",	  				// 4
	"RED_AMMO",		  				// 5
};

//
stock char g_sAmmoColors[][]=
{
	"GRAY_AMMO",
	"GREEN_AMMO",
	"BLUE_AMMO",
	"GOLD_AMMO",
	"RED_AMMO",
};

#define AMMO_SIZE 		5
